title: Samasthiti | We are makers
short_title: Samasthiti
permalink: /:title/
defaults:
  - scope:
      path: ""
    values:
      layout: "itemLayout"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "pagesLayout"
collections:
   projects:
    output: true
    permalink: "/projects/:path/"   
   services:
    output: true
    permalink: "/services/:path/"  
   blogs:
    output: true
    permalink: "/blogList/:path/"  
   homePagePhotos:
     output: false
   pages:
    output: true
    permalink: "/:name"
   designs:
    output: true
    permalink: "/designs/:path/"
   house-plans:
    output: true
    permalink: "/house-plans/:path/"
   interior-designs:
    output: true
    permalink: "/interior-designs/:path/"
   threeddesigns:
    output: true
    permalink: "/3ddesigns/:path/"
   constructions:
    output: true
    permalink: "/constructions/:path/"
   real-estates:
    output: true
    permalink: "/real-estates/:path/"
   buys:
    output: true
    permalink: "/buys/:path/"
   sells:
    output: true
    permalink: "/sells/:path/"

paginate: 7
paginate_path: "/page:num"

gems:
  - jekyll-paginate
